[PHP]
; Maximum allowed size of uploaded files
upload_max_filesize = 5000M

; Maximum size of POST data that PHP will accept
post_max_size = 5000M

; Maximum amount of memory a script may consume
memory_limit = 5000M

; Maximum execution time of each script, in seconds
max_execution_time = 3600

; Maximum input time for each script, in seconds
max_input_time = 3600
